# Generated by Django 4.1.1 on 2022-09-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date and Time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date and Time"
                    ),
                ),
                ("image", models.ImageField(upload_to="images", verbose_name="image")),
            ],
            options={"verbose_name": "Image", "verbose_name_plural": "Images",},
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=10)),
                ("birthday", models.DateTimeField()),
                ("phone", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_use_at", models.DateTimeField(auto_now=True)),
                ("last_use_station", models.TextField()),
                ("total_use", models.IntegerField()),
                ("accident", models.IntegerField(default=0)),
                ("point", models.IntegerField(default=0)),
            ],
        ),
    ]
