# Generated by Django 4.0.3 on 2022-09-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('birthday', models.DateTimeField()),
                ('phone', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_use_at', models.DateTimeField(auto_now=True)),
                ('last_use_station', models.TextField()),
                ('total_use', models.IntegerField()),
                ('accident', models.IntegerField(default=0)),
            ],
        ),
    ]
