# Generated by Django 4.1.1 on 2022-09-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_user_point"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, null=True)),
                ("image", models.ImageField(upload_to="")),
                ("created_at", models.DateField(blank=True, null=True)),
                ("updated_at", models.DateField(auto_now=True, null=True)),
            ],
        ),
    ]
