# Generated by Django 4.1.1 on 2022-09-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_image"),
    ]

    operations = [
        migrations.RemoveField(model_name="image", name="created_at",),
        migrations.RemoveField(model_name="image", name="image",),
        migrations.RemoveField(model_name="image", name="updated_at",),
        migrations.AddField(
            model_name="image",
            name="imgfile",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="image",
            name="title",
            field=models.TextField(max_length=40, null=True),
        ),
    ]
