# Generated by Django 4.1.1 on 2022-09-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_image_created_at_remove_image_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Creation Date and Time"
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Modification Date and Time"
                    ),
                ),
                ("image", models.ImageField(upload_to="images", verbose_name="image")),
            ],
            options={"verbose_name": "Image", "verbose_name_plural": "Images",},
        ),
        migrations.DeleteModel(name="Image",),
    ]
